apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-options: Prune=true,Delete=true

resources:
  - team-frontend.yaml
  - team-backend.yaml
  - team-platform.yaml
